<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="rajesh" failures="2" tests="2" name="Default test(failed)" time="0.124" errors="0" timestamp="25 Oct 2021 16:31:23 GMT">
  <testcase classname="org.flow.Flow" name="tc4" time="0.028">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.flow.Flow.tc4(Flow.java:42)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tc4 -->
  <testcase classname="org.flow.Flow" name="tc3" time="0.009">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.flow.Flow.tc3(Flow.java:33)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tc3 -->
  <testcase classname="org.flow.Flow" name="tc1" time="0.0">
    <ignored/>
  </testcase> <!-- tc1 -->
  <testcase classname="org.flow.Flow" name="tc2" time="0.0">
    <ignored/>
  </testcase> <!-- tc2 -->
</testsuite> <!-- Default test(failed) -->
